//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTopicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piezas
    {
        public int Id { get; set; }
        public string CodigoProveedor { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime timestamp { get; set; }
        public int EstadoFk { get; set; }
        public string CodigoProceso { get; set; }
        public Nullable<int> ResultadosFk { get; set; }
        public string TipoFk { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual TiposTablilla TiposTablilla { get; set; }
    }
}
